### ISSUE TITLE
Notes delete issue

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#105]
While a note along with attachment is deleted the record gets deleted however the response does not show properly. Also the delete confirm does not close.

**Comment by abhikchakraborty** [comment]
This was a bit complicated issue. While a note was having some attachment and while deleting the note it will use DataObject query method to get all the attachment and if there is any it will use a loop to delete the attachment entry from the DB. The delete method also uses the same object and uses query method. This eventually overwrites the existing select query which was used in the loop and hence it ends up with an error something as

```
 Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error' 
in /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOStatement.php:104\nStack trace:\n#0 
/var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOStatement.php(104): PDOStatement->fetch()\n#1 
/var/www/sqcrm/class/core/radria/DataObject.class.php(212): Doctrine\\DBAL\\Driver\\PDOStatement->fetch()\n#2 
/var/www/sqcrm/modules/Notes/Notes.class.php(321): DataObject->next()\n#3 
/var/www/sqcrm/class/core/radria/EventControler.class.php(166): Notes->eventAjaxDeleteNotes(Object(EventControler))\n#4 
/var/www/sqcrm/class/core/radria/EventControler.class.php(250): EventControler->Execute('Notes->eventAja...')\n#5 
/var/www/sqcrm/ajax_evctl.php(28): EventControler->listenEvents(Array)\n#6 {main}\n\nNext exception 
'Doctrine\\DBAL\\Driver\\PDOException' with message 'SQLSTATE[HY000]: General error' 
in /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOStatement.php:117\nStack trace:\n#0 
/var/www/sqcrm/class/core/radria/DataObject.class.php(212): Doctrine\\DBAL\\Driver\\PDOStateme in 
/var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOStatement.php on line 117

```

The fix is to use Doctrine native query method for handling the delete instead of the DataObject query method.

In addition also made some changes on delete event where after the delete it will use the Jquery `.remove()` method to remove the content instead of reloading the notes after notes.

Here is the PR https://github.com/sQcrm/sqcrm/pull/107
