### ISSUE TITLE
Send with us list view plugin

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#177]
The plugin
- should allow users to select `contacts`,`leads` or any entity for which the plugin is meant for
- should add the email to `send with us` via the api 
- should not add to `send with us` if no email or opt-out is set true.
- should add the custom information like `firstname`,`lastname` etc.
- should provide an option to select existing group while adding the email id, along with an option to create a new group and then add to that group.

#176

**Comment by abhikchakraborty** [comment]
Worked on this and there are some features which could not be implemented currently since they are currently not supported by the sendwithus api
- getting all the contacts from the group 
- sending email to a specific group contacts with a given template.

Since the above 2 are not possible we have to wait for this feature until they are implemented by sendwithus API.

In the current version we will have the feature where user can select some contacts and then send email to those selected contacts with the template (template should be created at sendwithus login)

Here is the PR https://github.com/sQcrm/sqcrm/pull/187
