### ISSUE TITLE
Product Page list issue

### ISSUE THREAD

**Issue by vivekshekar** [sQcrm/sqcrm#232]
@abhikchakraborty 

While testing found that on product page we are getting an error from ajax cal,
I am attaching the error with this note. 

![screenshot from 2016-11-09 12-26-09](https://cloud.githubusercontent.com/assets/1007234/20129738/00bf1308-a678-11e6-971f-0f1ace1daf00.png)

and the error log show the below error, 

`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #14 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sqcrm.products_pricing.idproducts_pricing' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOConnection.php:104\nStack trace:\n#0 /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('select `product...')\n#1 /var/www/sqcrm/Doctrine/Doctrine/DBAL/Connection.php(829): Doctrine\\DBAL\\Driver\\PDOConnection->query('select `product...')\n#2 /var/www/sqcrm/class/core/radria/DataObject.class.php(289): Doctrine\\DBAL\\Connection->executeQuery('select `product...', Array, Array)\n#3 /var/www/sqcrm/class/datadisplay/DataDisplay.class.php(323): DataObject->query('select `product...')\n#4 /var/www/sqcrm/listdata.php(247): DataDisplay->display_data('12')\n#5 {main}\n\nNext Doctrine\\DBAL\\Driver\\PDOException: SQLSTATE[42000 in /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115, referer: http://sqcrm.localhost/modules/Products/index`

**Comment by abhikchakraborty** [comment]
@vivekshekar yes its because of the product module listing query. The query was doing `group by products.idproducts` and in addition it was selecting a lot of data with only one aggregate function. This was allowed prior mysql 5.7 , but since mysql 5.7 its more strict and it has to follow the standard sql for aggregate functions, i.e. all the non aggregated columns selected in the query must be in the group by clause if you choose to apply `group by`

The fix for the query would take a while since there is `one-to-many` relation and we would require to minimize the number of query being executed while loading the list data.

In the mean while the solution should be to disable full group by option https://serverpilot.io/community/articles/how-to-disable-strict-mode-in-mysql-5-7.html

**Comment by abhikchakraborty** [comment]
@vivekshekar please close the issue if the above solution fixes the problem. We will work more into the issue later to make the query compatible with `Mysql 5.7`
