### ISSUE TITLE
Built-in reports

### ISSUE THREAD

**Issue by abhikchakraborty** [sQcrm/sqcrm#82]
We need to have some built-in reports for the analytic.
The reports are mostly user centric and should reflect some matrix.

**Comment by sQcrm** [comment]
This should also allow **developers** to create more reports without having to change the core of the report module. The idea is to provide a way for the developers so that they can write code to create more reports as per the business need which are not covered by the Report module custom report section.
The reports could be very complex or even simple, however its impossible to know the reports a business will require and hence this feature.

- The first thing is to create an architecture for this reports.
- And once the architecture is ready we will create a series of reports and will call then inbuilt report for the sQcrm. These reports however cant be customized the way currently done on report modules however developers can always change the shape of those reports. Or create their own.

**Comment by abhikchakraborty** [comment]
The base for the custom reports are ready for review https://github.com/sQcrm/sqcrm/pull/99
